//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindDuplicateMp3s.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FindDuplicateMp3s.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon _1308839077_MP3 {
            get {
                object obj = ResourceManager.GetObject("_1308839077_MP3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon _1308839315_Folder_Searches {
            get {
                object obj = ResourceManager.GetObject("_1308839315_Folder_Searches", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon _1308839354_iSync {
            get {
                object obj = ResourceManager.GetObject("_1308839354_iSync", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon _1308839380_Properties {
            get {
                object obj = ResourceManager.GetObject("_1308839380_Properties", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon _1308839578_Trash_Recyclebin_Empty_Closed {
            get {
                object obj = ResourceManager.GetObject("_1308839578_Trash_Recyclebin_Empty_Closed", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon _1308839897_Folder_Music_2 {
            get {
                object obj = ResourceManager.GetObject("_1308839897_Folder_Music_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon _1308840297_vlc {
            get {
                object obj = ResourceManager.GetObject("_1308840297_vlc", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1308840301_vlc {
            get {
                object obj = ResourceManager.GetObject("_1308840301_vlc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon _1308840393_Gnome_Undelete_64 {
            get {
                object obj = ResourceManager.GetObject("_1308840393_Gnome_Undelete_64", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon _1308840694_Cancel {
            get {
                object obj = ResourceManager.GetObject("_1308840694_Cancel", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon _1308840742_Redo {
            get {
                object obj = ResourceManager.GetObject("_1308840742_Redo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon _1308840793_Search {
            get {
                object obj = ResourceManager.GetObject("_1308840793_Search", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1308841035_Undo {
            get {
                object obj = ResourceManager.GetObject("_1308841035_Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1308841068_Play {
            get {
                object obj = ResourceManager.GetObject("_1308841068_Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1308841085_Find {
            get {
                object obj = ResourceManager.GetObject("_1308841085_Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1308841166_Search {
            get {
                object obj = ResourceManager.GetObject("_1308841166_Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon _1308842465_Add {
            get {
                object obj = ResourceManager.GetObject("_1308842465_Add", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309256835_Delete {
            get {
                object obj = ResourceManager.GetObject("_1309256835_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon _1309256841_Delete {
            get {
                object obj = ResourceManager.GetObject("_1309256841_Delete", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete files?.
        /// </summary>
        internal static string Do_you_want_to_delete_files {
            get {
                return ResourceManager.GetString("Do_you_want_to_delete_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files succesfuly deleted.
        /// </summary>
        internal static string Files_succesfuly_deleted {
            get {
                return ResourceManager.GetString("Files_succesfuly_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files will be deleted permanetly.
        /// </summary>
        internal static string Files_will_be_deleted_permanetly {
            get {
                return ResourceManager.GetString("Files_will_be_deleted_permanetly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file deleted..
        /// </summary>
        internal static string No_file_deleted_ {
            get {
                return ResourceManager.GetString("No_file_deleted_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning all files....
        /// </summary>
        internal static string ScanningAllFiles {
            get {
                return ResourceManager.GetString("ScanningAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search now.
        /// </summary>
        internal static string SearchNow {
            get {
                return ResourceManager.GetString("SearchNow", resourceCulture);
            }
        }
    }
}
